# Generated by Django 4.1.7 on 2023-02-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Globalnet Bronze - 500 BDT / month, 12 months'), ('silver', 'Globalnet Silver - 750 BDT / month, 12 months'), ('gold', 'Globalnet Gold - 1500 BDT / month, no contract')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contract_period', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
