# Generated by Django 4.1.7 on 2023-02-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
    ]
