# Generated by Django 4.1.7 on 2023-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
