# Generated by Django 4.1.7 on 2023-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0002_phonenumber_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
